# Generated by Django 5.1.2 on 2024-10-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
