# Generated by Django 5.1.2 on 2024-10-25 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0007_alter_token_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('course_code', models.CharField(max_length=10, unique=True)),
                ('course_units', models.PositiveIntegerField()),
                ('course_join_code', models.CharField(max_length=10, unique=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.lecturer')),
                ('students', models.ManyToManyField(related_name='courses', to='account.student')),
            ],
        ),
    ]
