# Generated by Django 5.1.2 on 2024-10-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0002_alter_course_lecturer_alter_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_open',
            field=models.BooleanField(default=True),
        ),
    ]
