# Generated by Django 5.1.2 on 2024-10-27 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0003_course_course_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_units',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
