# Generated by Django 5.1.2 on 2024-11-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
