# Generated by Django 5.1.2 on 2024-10-27 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_rename_testcases_testcase_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='score',
        ),
        migrations.CreateModel(
            name='ExampleTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment')),
            ],
        ),
    ]
