# Generated by Django 5.1.2 on 2024-12-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_assignment_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='language_id',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='programming_language',
            field=models.CharField(null=True),
        ),
    ]
