# Generated by Django 5.1.2 on 2024-10-27 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_remove_testcase_score_exampletestcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='max_score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
