# Generated by Django 5.1.2 on 2024-12-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_testcase_is_hidden'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleTestCase',
        ),
    ]
