# Generated by Django 5.1.2 on 2024-10-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_alter_assignment_max_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampletestcase',
            name='input',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='exampletestcase',
            name='output',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output',
            field=models.JSONField(),
        ),
    ]
