# Generated by Django 5.1.2 on 2024-10-28 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_alter_exampletestcase_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampletestcase',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_test_cases', to='assignment.assignment'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='assignment.assignment'),
        ),
    ]
