# Generated by Django 5.1.2 on 2024-10-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_alter_exampletestcase_assignment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.RemoveField(
            model_name='submission',
            name='llm_feedback',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='submission',
            name='results',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
