# Generated by Django 5.1.2 on 2025-03-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_assignment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='language_name',
            field=models.CharField(null=True),
        ),
    ]
