# Generated by Django 5.1.2 on 2024-10-30 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_alter_submission_results_alter_submission_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Draft',
        ),
    ]
