# Generated by Django 5.1.2 on 2025-04-09 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_assignment_language_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='language_name',
        ),
    ]
