# Generated by Django 5.1.2 on 2024-10-31 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0009_delete_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampletestcase',
            name='input',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exampletestcase',
            name='output',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output',
            field=models.CharField(max_length=100),
        ),
    ]
