# Generated by Django 5.1.2 on 2025-04-13 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0009_remove_assignment_language_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assignment.submission'),
        ),
    ]
