# Generated by Django 5.1.2 on 2024-10-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0010_alter_exampletestcase_input_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_best',
            field=models.BooleanField(default=True),
        ),
    ]
