# Generated by Django 5.1.2 on 2024-11-01 19:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0011_submission_is_best'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(condition=models.Q(('is_best', True)), fields=('assignment', 'student'), name='unique_submission'),
        ),
    ]
