# Generated by Django 5.1.2 on 2024-11-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0012_submission_unique_submission'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='submission',
            name='unique_submission',
        ),
    ]
