# Generated by Django 5.1.2 on 2024-11-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0013_remove_submission_unique_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='is_best',
            field=models.BooleanField(),
        ),
    ]
