# Generated by Django 5.1.2 on 2024-11-03 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0014_alter_submission_is_best'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='is_best',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['assignment', 'student', 'is_best'], name='assignment__assignm_5e7027_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', 'assignment'], name='assignment__student_59de3a_idx'),
        ),
    ]
